import React, { useState } from 'react';
import { AgentChat } from './components/AgentChat';
import { Terminal } from './components/Terminal';
import { CodeWorkspace } from './components/CodeWorkspace';
import { SystemLog } from './components/SystemLog';
import { Dashboard } from './components/Dashboard';
import { ProjectDetails } from './components/ProjectDetails';
import { LogLevel, Project } from './types';
import { logger } from './services/logger';
import { LayoutGrid, ArrowLeft } from 'lucide-react';

// Default demo code
const DEFAULT_CODE = `<!DOCTYPE html>
<html>
<head>
    <style>
        body { background: #1a1a1a; color: white; display: flex; justify-content: center; align-items: center; height: 100vh; font-family: sans-serif; }
        .card { padding: 2rem; background: #333; border-radius: 1rem; text-align: center; }
        h1 { color: #00ff88; }
    </style>
</head>
<body>
    <div class="card">
        <h1>Hello World</h1>
        <p>Generated by Nexus AI</p>
    </div>
</body>
</html>`;

const App: React.FC = () => {
  const [view, setView] = useState<'dashboard' | 'workspace' | 'details'>('dashboard');
  const [activeProject, setActiveProject] = useState<Project | null>(null);
  const [code, setCode] = useState(DEFAULT_CODE);
  const [terminalOutput, setTerminalOutput] = useState<string | null>(null);

  const handleOpenProject = (project: Project) => {
    setActiveProject(project);
    // Simulate loading project code
    if (project.framework === 'react') {
        setCode(`// Nexus AI Project: ${project.name}
// Framework: React
import React from 'react';
import ReactDOM from 'react-dom/client';

function App() {
  return (
    <div className="app">
      <h1>${project.name}</h1>
      <p>Status: ${project.status}</p>
    </div>
  );
}

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(<App />);`);
    } else {
        setCode(DEFAULT_CODE.replace('Nexus AI', project.name));
    }
    setView('workspace');
    logger.log(`Opened project workspace: ${project.name}`, LogLevel.INFO, 'SYSTEM');
  };

  const handleViewProjectDetails = (project: Project) => {
      setActiveProject(project);
      setView('details');
      logger.log(`Viewing details for project: ${project.name}`, LogLevel.INFO, 'SYSTEM');
  };

  const handleNavigateBack = () => {
    setView('dashboard');
    setActiveProject(null);
  };

  const handleCodeUpdate = (newCode: string) => {
    setCode(newCode);
    logger.log('Code content updated by Agent', LogLevel.INFO, 'CORE');
  };

  const handleTerminalCommand = (cmd: string) => {
    logger.log(`Agent executing shell command: ${cmd}`, LogLevel.WARN, 'CORE');
    // Simulate some simple responses for demo purposes if the agent sends commands
    if (cmd.includes('npm install')) {
        setTerminalOutput(`\n[NPM] Installing dependencies for ${cmd.split(' ')[2] || 'project'}...\n[NPM] Added 42 packages in 1.4s`);
    } else if (cmd.includes('ls')) {
        setTerminalOutput('\nindex.html\nstyle.css\napp.js\npackage.json');
    } else {
        setTerminalOutput(`\n$ ${cmd}\n> Command executed successfully.`);
    }
  };

  return (
    <div className="h-screen w-screen bg-black text-slate-200 flex flex-col overflow-hidden">
        {/* Top Navigation / Status Bar */}
        <header className="h-12 bg-slate-950 border-b border-slate-800 flex items-center justify-between px-6 shrink-0 z-20 shadow-md relative">
            <div className="flex items-center gap-6">
                <div className="flex items-center gap-3 cursor-pointer" onClick={() => setView('dashboard')}>
                    <div className="w-4 h-4 rounded-sm bg-gradient-to-tr from-indigo-500 to-cyan-500 shadow-[0_0_15px_rgba(99,102,241,0.5)]"></div>
                    <h1 className="font-bold tracking-widest text-lg bg-clip-text text-transparent bg-gradient-to-r from-indigo-400 to-cyan-400">NEXUS</h1>
                </div>
                
                {/* Navigation Breadcrumbs / Tabs */}
                <div className="flex items-center h-full gap-1 ml-4 border-l border-slate-800 pl-4">
                    <button 
                        onClick={() => setView('dashboard')}
                        className={`flex items-center gap-2 px-3 py-1.5 rounded-md text-xs font-medium transition-all ${view === 'dashboard' ? 'bg-indigo-500/10 text-indigo-400' : 'text-slate-500 hover:text-slate-300'}`}
                    >
                        <LayoutGrid size={14} />
                        Dashboard
                    </button>
                    {activeProject && (
                        <>
                            <span className="text-slate-700">/</span>
                            <div className={`flex items-center gap-2 px-3 py-1.5 rounded-md text-xs font-medium transition-all ${view === 'details' ? 'bg-indigo-500/10 text-indigo-400' : 'text-slate-500 hover:text-slate-300 cursor-pointer'}`}
                                 onClick={() => handleViewProjectDetails(activeProject)}
                            >
                                {activeProject.name}
                            </div>
                            {view === 'workspace' && (
                                <>
                                    <span className="text-slate-700">/</span>
                                    <div className="flex items-center gap-2 px-3 py-1.5 rounded-md text-xs font-medium bg-indigo-500/10 text-indigo-400">
                                        Workspace
                                    </div>
                                </>
                            )}
                        </>
                    )}
                </div>
            </div>

            <div className="flex gap-4 text-xs font-mono text-slate-500">
                <span className="flex items-center gap-1"><span className="w-1.5 h-1.5 rounded-full bg-emerald-500"></span> CPU: 12%</span>
                <span className="flex items-center gap-1"><span className="w-1.5 h-1.5 rounded-full bg-emerald-500"></span> MEM: 4.2GB</span>
            </div>
        </header>

        {/* Main Content Grid */}
        <main className="flex-1 flex overflow-hidden bg-slate-950/50 relative">
            {view === 'dashboard' ? (
                <Dashboard onOpenProject={handleOpenProject} onViewDetails={handleViewProjectDetails} />
            ) : view === 'details' && activeProject ? (
                <ProjectDetails 
                    project={activeProject} 
                    onBack={handleNavigateBack}
                    onOpenWorkspace={() => handleOpenProject(activeProject)}
                />
            ) : (
                <div className="w-full h-full flex p-2 gap-2 animate-in fade-in duration-300">
                    {/* Left Column: Chat & System Log */}
                    <div className="w-[400px] flex flex-col gap-2 shrink-0">
                        <div className="flex-1 min-h-0">
                            <AgentChat 
                                onCodeReceived={handleCodeUpdate}
                                onTerminalCommand={handleTerminalCommand}
                            />
                        </div>
                        <div className="h-1/3 min-h-[200px] border border-slate-800 rounded-lg overflow-hidden shadow-lg">
                            <SystemLog />
                        </div>
                    </div>

                    {/* Center/Right Column: Workspace */}
                    <div className="flex-1 flex flex-col gap-2 min-w-0">
                        
                        {/* Code Editor Area */}
                        <div className="flex-1 min-h-0">
                            <CodeWorkspace code={code} onCodeChange={setCode} />
                        </div>

                        {/* Terminal Area */}
                        <div className="h-[250px] shrink-0">
                            <Terminal externalOutput={terminalOutput} />
                        </div>
                    </div>
                </div>
            )}
        </main>
    </div>
  );
};

export default App;